[[plugins]]
  package = "@netlify/plugin-nextjs"
[[plugins]]
  package = "@algolia/netlify-plugin-crawler"
    [plugins.inputs]
    branches = ['master', 'develop', 'algoliatwo', 'feat/add-algolia']
    disabled = false
    renderJavaScript = true


[functions]
  directory = "api/functions/"
